"""empty message

Revision ID: 0534d1a1c8d6
Revises: e2520ea04132
Create Date: 2017-10-15 08:03:48.191459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0534d1a1c8d6'
down_revision = 'e2520ea04132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deploy_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('webproject', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('log_file', sa.String(length=64), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('execute_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deploy_info_name'), 'deploy_info', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deploy_info_name'), table_name='deploy_info')
    op.drop_table('deploy_info')
    # ### end Alembic commands ###
