"""empty message

Revision ID: 1499dd285147
Revises: 4c3dd8e36ab8
Create Date: 2017-09-09 14:14:40.341182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1499dd285147'
down_revision = '4c3dd8e36ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_info', 'webproject',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('application_info', 'webserver',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_info', 'webserver',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('application_info', 'webproject',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
