"""empty message

Revision ID: 1f8048c8a2c9
Revises: 447fe8881937
Create Date: 2017-09-04 11:29:55.919174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8048c8a2c9'
down_revision = '447fe8881937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department', sa.String(length=256), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'department')
    # ### end Alembic commands ###
