"""empty message

Revision ID: 210f88d69150
Revises: 1499dd285147
Create Date: 2017-09-11 09:53:25.926608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210f88d69150'
down_revision = '1499dd285147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_info', sa.Column('webserver', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_sys_info_webserver'), 'sys_info', ['webserver'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_info_webserver'), table_name='sys_info')
    op.drop_column('sys_info', 'webserver')
    # ### end Alembic commands ###
