"""empty message

Revision ID: 24d54dbf9d0e
Revises: e098e4cdef65
Create Date: 2017-08-21 09:35:58.857588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24d54dbf9d0e'
down_revision = 'e098e4cdef65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('sys', sa.String(length=512), nullable=True),
    sa.Column('usage', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_info_ip'), 'sys_info', ['ip'], unique=False)
    op.alter_column('user', 'hash_password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hash_password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.drop_index(op.f('ix_sys_info_ip'), table_name='sys_info')
    op.drop_table('sys_info')
    # ### end Alembic commands ###
