"""empty message

Revision ID: 3291bac745da
Revises: 210f88d69150
Create Date: 2017-09-22 15:45:47.326248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3291bac745da'
down_revision = '210f88d69150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_info', sa.Column('webpath', sa.String(length=128), nullable=False))
    op.add_column('application_info', sa.Column('webport', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_info', 'webport')
    op.drop_column('application_info', 'webpath')
    # ### end Alembic commands ###
