"""empty message

Revision ID: 447fe8881937
Revises: 24d54dbf9d0e
Create Date: 2017-08-21 11:16:28.415859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '447fe8881937'
down_revision = '24d54dbf9d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_info', sa.Column('application', sa.String(length=64), nullable=True))
    op.drop_column('sys_info', 'usage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_info', sa.Column('usage', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('sys_info', 'application')
    # ### end Alembic commands ###
