"""empty message

Revision ID: 4c3dd8e36ab8
Revises: 0acd7f17cdc6
Create Date: 2017-09-09 14:11:22.809103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c3dd8e36ab8'
down_revision = '0acd7f17cdc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_info', sa.Column('webserver', sa.String(length=64), nullable=True))
    op.drop_column('application_info', 'applicationserver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_info', sa.Column('applicationserver', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('application_info', 'webserver')
    # ### end Alembic commands ###
