"""empty message

Revision ID: f5c5a2115207
Revises: bb11a594db6c
Create Date: 2017-08-17 10:21:00.601722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5c5a2115207'
down_revision = 'bb11a594db6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_password', sa.String(length=64), nullable=False))
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.drop_index('ix_user_name', table_name='user')
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_column('user', 'hash_password')
    # ### end Alembic commands ###
